"""scm_frontier: spectral recoverability frontier tools for panel causal inference."""

from .dgps import ALIGNMENTS, NOISE_LAWS, generate_panel
from .estimators import (
    DEFAULT_MC_LAMBDAS,
    DEFAULT_RIDGE_LAMBDAS,
    donor_mean,
    mc_nn_cv,
    oracle_predict,
    rank_selector,
    ridge_sc,
    scm_simplex,
    select_rank_gap_ratio,
    sdid,
    spectral_sc,
    spectral_sc_full,
    unit_scatter,
)
from .diagnostics import (
    alignment_energy,
    classical_trend_ttest,
    cv_rank_selector,
    gate_lrv,
    gated_rank,
    invert_bbp,
    kink_breakpoint,
    pre_trends_post_test,
    resid_statistic,
    robust_row_scales,
    scree,
    simulated_null_z,
    spike_estimates,
    tw_mu_nu,
    tw_statistic,
    z_boot_pvalue,
    z_perm_pvalue,
    z_shift_pvalue,
    z_tw_pvalue,
)
from .experiment import METHODS, ROW_COLS, run_cell, run_rep

__all__ = [
    "ALIGNMENTS",
    "NOISE_LAWS",
    "generate_panel",
    "DEFAULT_MC_LAMBDAS",
    "DEFAULT_RIDGE_LAMBDAS",
    "donor_mean",
    "mc_nn_cv",
    "oracle_predict",
    "rank_selector",
    "ridge_sc",
    "scm_simplex",
    "select_rank_gap_ratio",
    "sdid",
    "spectral_sc",
    "spectral_sc_full",
    "unit_scatter",
    "alignment_energy",
    "classical_trend_ttest",
    "cv_rank_selector",
    "gated_rank",
    "invert_bbp",
    "resid_statistic",
    "scree",
    "simulated_null_z",
    "spike_estimates",
    "tw_mu_nu",
    "tw_statistic",
    "z_boot_pvalue",
    "z_perm_pvalue",
    "z_shift_pvalue",
    "z_tw_pvalue",
    "gate_lrv",
    "kink_breakpoint",
    "pre_trends_post_test",
    "robust_row_scales",
    "METHODS",
    "ROW_COLS",
    "run_cell",
    "run_rep",
]
